rango/urls.py
from django.urls import path
from . import views

app_name = 'rango'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('add_category/', views.add_category, name='add_category'),
    path('<category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('category/<category_name_slug>', views.show_category, name='show_category'),
    path('goto/', views.track_url, name='goto'),
    path('register_profile/', views.register_profile, name='register_profile'),
    path('profile/<username>', views.profile, name='profile'),
    path('profiles/', views.list_profiles, name='list_profiles'),
    path('like/', views.like_category, name='like_category'),
    #path('register/', views.register, name='register'),
    #path('login/', views.user_login, name='login'),
    #path('logout/', views.user_logout, name='logout',)

]

rango_link_directory/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rango import views
from registration.backends.simple.views import RegistrationView


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return 'rango:register_profile'


urlpatterns = [
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('admin/', admin.site.urls),
    path('', views.index),
    path('rango/', include('rango.urls')),
    path('accounts/', include('registration.backends.default.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    max_length = 128
    name = models.CharField(max_length=max_length, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.views < 0:
            self.views = 0
        #self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Category, Page, UserProfile, User
from .form import CategoryForm, PageForm, UserForm, UserProfileForm
from django.urls import reverse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.shortcuts import redirect


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', 1))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).days > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits


# Create your views here.


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context=context_dict)
    return response


def about(request):
    context_dict = {'yourname': 'امین زمانی'}
    print(request.method)
    print(request.user)
    return render(request, 'rango/about.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        category.views += 1
        category.save()
        page = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = page
        context_dict['category'] = category

    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None

    return render(request, 'rango/category.html', context=context_dict)


@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse(index(request)))
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return HttpResponseRedirect(reverse('rango:show_category', args=(category_name_slug,)))
        else:
            print(form.errors)
    return render(request, 'rango/add_page.html', {'form': form, 'category': category})


def track_url(request):
    page_id = None
    if request.method == "GET":
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
    try:
        page = Page.objects.get(id=page_id)
        print(page.url)
        page.views += 1
        page.save()
        return redirect(page.url)
    except Page.DoesNotExist:
        return HttpResponseRedirect(reverse('rango:index'))


@login_required
def register_profile(request):
    form = UserProfileForm()
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            return redirect('rango:index')
        else:
            print(form.errors)

    context_dict = {'form': form}
    return render(request, 'rango/profile_registration.html', context_dict)


@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('rango:index')

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm({'website': userprofile.website, 'picture': userprofile.picture})
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)
    return render(request, 'rango/profile.html', {'userprofile': userprofile, 'selecteduser': user, 'form': form})


@login_required
def list_profiles(request):
    userprofile_list = UserProfile.objects.all()
    return render(request, 'rango/list_profiles.html', {'userprofile_list': userprofile_list})


@login_required
def like_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']
    likes = 0
    if cat_id:
        cat = Category.objects.get(id=int(cat_id))
        if cat:
            likes = cat.likes + 1
            cat.likes = likes
            cat.save()
    return HttpResponse(likes)
#def register(request):
#    registered = False
#    if request.method == 'POST':
#        user_form = UserForm(data=request.POST)
#        profile_form = UserProfileForm(data=request.POST)

#        if user_form.is_valid() and profile_form.is_valid():
#            user = user_form.save()
#            user.set_password(user.password)
#            user.save()
#            profile = profile_form.save(commit=False)
#            profile.user = user
#            if 'picture' in request.FILES:
#                profile.picture = request.FILES['picture']
#            profile.save()
#            registered = True
#        else:
#            print(user_form.errors, profile_form.errors)
#    else:
#        user_form = UserForm()
#        profile_form = UserProfileForm()
#    return render(request, 'rango/register.html', {'user_form': user_form, 'profile_form': profile_form,
#                                                   'registered': registered})


#def user_login(request):
#    if request.method == 'POST':
#        username = request.POST.get('username')
#        password = request.POST.get('password')
#        user = authenticate(username=username, password=password)

#        if user:
#            if user.is_active:
#                login(request, user)
#                return HttpResponseRedirect(reverse('rango:index'))
#            else:
#               return HttpResponse('Your Rango account is disabled.')
#        else:
#            print("Invalid login details: {0}, {1}".format(username, password))
#            return HttpResponse("Invalid login details supplied.")
#    else:
#        return render(request, 'rango/login.html', {})


#@login_required
#def user_logout(request):
    #logout(request)
    #return HttpResponseRedirect(reverse('rango:index'))

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}


{% block title_block %}

درباره من

{% endblock %}

{% block body_block %}

<img src="{% static 'images/About-Us.jpg' %}" alt="About Me Picture" width="600px" height="200px" align="center">
<br />
<p>
    این پروژه توسط
 {{ yourname }} ساخته شده.
</p>
<br />
<img src="{{MEDIA_URL}}cat.webp" alt="Picture of cat">



{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load bootstrap_toolkit %}
{% load static %}


{% block title_block %}

اضافه کردن موضوع

{% endblock %}

{% block body_block %}
<style>
    [type="submit"]:not(:disabled), button:not(:disabled) {
    cursor: pointer;
    float: right;
    position: relative;
    right: 55%;
    bottom: 35PX;
}

</style>

<h1>اضافه کردن موضوع</h1>
<div>
    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn-primary" type="submit" name="submit" value="اضافه کردن موضوع" />
    </form>

</div>

{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load bootstrap_toolkit %}
{% load static %}


{% block title_block %}

اضافه کردن صفحه
{% endblock %}

{% block body_block %}

{% if category %}
    <form role="form" id="page_form" method="post" action="/rango/{{category.slug}}/add_page/">
        <h2 class="form-signin-heading"> اضافه کردن صفحه به <a href="/rango/category/{{category.slug}}/"> {{ category.name }}</a></h2>
        {% csrf_token %}
        {% bootstrap_form form %}
        <br/>
        <button class="btn btn-lg btn-primary btn-block" type="submit" name="submit">اضافه کردن صفحه</button>
    </form>
{% else %}
    <p>این موضوع وجود نداره!</p>
{% endif %}

{% endblock %}

templates/rango/base.html
<!doctype html>
{% load static %}
{% load bootstrap_toolkit %}
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Amin Zamani">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>رنگو - {% block title_block %}هر آن‌چه بخواهید!{% endblock %}</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/dashboard/">

    <!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>

    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.3/examples/dashboard/dashboard.css" rel="stylesheet">
    <link href="{% static 'css/bootstrap-rtl.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-rtl.min' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'rango:index' %}">رنگو - هر چه بخواهید!</a>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
       {% if user.is_authenticated %}
        <a href="{% url 'auth_logout' %}?next=/rango/">خروج</a>
        {% else %}
      <a class="nav-link" href="{% url 'auth_login' %}">ورود</a>
        {% endif %}
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'rango:index' %}">
              <span data-feather="home"></span>
              خانه <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">
              <span data-feather="file"></span>
              درباره من
            </a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:profile' user.username %}">
              <span data-feather="file"></span>
              پروفایل من
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:add_category' %}">
              <span data-feather="shopping-cart"></span>
              اضافه کردن موضوع
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:list_profiles' %}">
              <span data-feather="users"></span>
              همه کاربران
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'registration_register' %}">
              <span data-feather="users"></span>
              ثبت‌نام
            </a>
          </li>
        {% endif %}
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>۵ موضوع برتر</span>

        </h6>
        <ul class="nav flex-column mb-2">
          {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <br />


      {% block body_block %}
              {% endblock %}
    </main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.3/examples/dashboard/dashboard.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
        <script src="{% static 'js/rango-ajax.js' %}"></script></body>
</html>

templates/rango/base_bootstrap.html
<!doctype html>
{% load static %}
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Amin Zamani">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/dashboard/">

    <!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.3/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Rango</a>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
       {% if user.is_authenticated %}
        <a href="{% url 'auth_logout' %}?next=/rango/">Sign Out</a>
        {% else %}
      <a class="nav-link" href="{% url 'auth_login' %}">Sign In</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'rango:index' %}">
              <span data-feather="home"></span>
              Home <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">
              <span data-feather="file"></span>
              About
            </a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:add_category' %}">
              <span data-feather="shopping-cart"></span>
              Add New Category
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'registration_register' %}">
              <span data-feather="users"></span>
              Sign Up
            </a>
          </li>

        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Top 5</span>

        </h6>
        <ul class="nav flex-column mb-2">
          {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Home</h1>

      </div>

      {% block body_block %}
              {% endblock %}
    </main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.3/examples/dashboard/dashboard.js"></script></body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}


{% block title_block %}

{{ category.name }}

{% endblock %}

{% block body_block %}

{% if category %}
    <h1> {{ category.name }} </h1>
    <div>
        <strong id="like_count"> {{ category.likes }} </strong> نفر این موضوع را پسنیدیده‌اند
        {% if user.is_authenticated %}
            <button id="likes" data-catid="{{ category.id }}" class="btn btn-primary btn-sm" type="button">
                می‌پسندم!
            </button>
        {% endif %}
    </div>
<br />
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
                ({{ page.views }} بار دیده شده)
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <strong> هیچ صفحه‌ای برای این موضوع ثبت نشده است.</strong>
    {% endif %}
        {% if user.is_authenticated %}
            <div>
                <button class="btn btn-primary btn-sm" type="button" onclick="window.location.href ='/rango/{{category.slug}}/add_page';">
                    افزودن صفحه</button>
            </div>
        {% endif %}
    {% else %}
    <strong> این موضوع وجود ندارد</strong>

    {% endif %}


{% endblock %}

templates/rango/cats.html
<ul>
    {% if cats %}
    {% for c in cats %}
        {% if c == act_cat %}
            <strong>
            <li> <a href="{% url 'rango:show_category' c.slug %}"> {{ c.name }} </a> </li>
            </strong>
         {% else %}
            <li> <a href="{% url 'rango:show_category' c.slug %}"> {{ c.name }} </a> </li>
        {% endif %}
    {% endfor %}
    {% else %}
    <li> <strong>هیچ موضوعی وجود ندارد</strong> </li>
    {% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}




{% block body_block %}

 <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">رنگو می‌گه ...</h1>
      {% if user.is_authenticated %}
            چطوری {{ user.username }}؟
        {% else %}
            سلام رفیق!
        {% endif %}

        <p> بازدیدکنندگان از سایت: {{ visits }}</p>
    </div>
  </div>

 <div class="row marketing">
			<div class="col-lg-6">
				<h4>محبوب‌ترین موضوعات</h4>
				<p>
		         	{% if categories %}
		             <ul class="list-group">
		                 {% for category in categories %}
		                 	<li class="list-group-item"><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a> <span class="badge badge-pill badge-primary">{{category.likes}}</span></li>
		                 {% endfor %}
		             </ul>
		        {% else %}
		             <strong>هیچ موضوعی وجود نداره!</strong>
		        {% endif %}

				</p>

			</div>
			<div class="col-lg-6">
				<h4>پربازدیدترین صفحات</h4>
				<p>
				{% if pages %}
				<ul class="list-group">
				{% for page in pages %}
				 <li class="list-group-item"><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a> <span class="badge badge-pill badge-primary">{{page.views}}</span></li>
				 {% endfor %}
				 </ul>
				{% else %}
				<strong>هیچ صفحه‌ای وجود نداره!</strong>
			 {% endif %}
				</p>
			</div>
		</div>


    <br />
    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    </div>
{% endblock %}

templates/rango/list_profiles.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %} کاربران رنگو {% endblock %}

{% block body_block %}
    <h1>کاربران رنگو</h1>
    <div class="panel">
        {% if userprofile_list %}
        <div class="panel-heading">
            <!-- Display search results in an ordered list -->
            <div class="panel-body">
                <div class="list-group">
                {% for listuser in userprofile_list %}
                    <div class="list-group-item">
                         <h4 class="list-group-item-heading">
                            <a href="{% url 'rango:profile' listuser.user.username %}">
                            {{ listuser.user.username }}</a>
                         </h4>
                        {% if listuser.picture %}
                            <img src="{{ MEDIA_URL }}{{ listuser.picture }}" width="64" height="64" />
                        {% else %}
                            <img src="http://lorempixel.com/64/64/people/" />
                        {% endif %}
                    </div>

                    {% endfor %}
                </div>
            </div>
        </div>
        {% else %}
        <p>There are no users for the site.</p>
        {% endif %}
    </div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}

{% load static %}

    {% block title_block %}
        Login
    {% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />
        <input type="submit" value="submit" />
    </form>
{% endblock %}

templates/rango/profile.html
{% extends 'rango/base.html' %}

{% load static %}

{% block title_block %} پروفایل {{ selecteduser.username }} {% endblock %}

{% block body_block %}
<h1>پروفایل {{ selecteduser.username }}</h1>
<img src="{{ MEDIA_URL }}{{ userprofile.picture }}"
    width="300"
    height="300"
    alt="{{ selecteduser.username }}" />
<br/>
<div>
    {% if selecteduser.username == user.username %}
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="بروزرسانی" />
        </form>
    {% else %}
        <p><strong>وب‌سایت:</strong> <a href="{{ userprofile.website }}">
        {{ userprofile.website }}</a></p>
    {% endif %}
</div>
<div id="edit_profile"></div>

{% endblock %}

templates/rango/profile_registration.html
{% extends "rango/base.html" %}

{% block title_block %}
ثبت‌نام - مرحله دوم
{% endblock %}

{% block body_block %}
    <h1> ثبت‌نام - مرحله دوم</h1>
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ذخیره">
    </form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
Register
{% endblock %}

{% block body_block %}

    <h1> About Page </h1>
    {% if registered %}
        Rango Says: <strong> Thank you for registering! </strong>
        <a href="{% url 'rango:index' %}"> Return to the Homepage</a> <br />
    {% else %}
        Rango says: <strong> Register here! </strong>
        <form action="{% url 'rango:register' %}" id="user_form" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="register">
        </form>
    {% endif %}
{% endblock %}